// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mihausik.bil;

import com.mihausik.bil.Clientservice;
import com.mihausik.bil.Tempblock;
import com.mihausik.bil.TempblockDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TempblockDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TempblockDataOnDemand: @Component;
    
    private Random TempblockDataOnDemand.rnd = new SecureRandom();
    
    private List<Tempblock> TempblockDataOnDemand.data;
    
    public Tempblock TempblockDataOnDemand.getNewTransientTempblock(int index) {
        Tempblock obj = new Tempblock();
        setClientservice(obj, index);
        setStartblock(obj, index);
        setStopblock(obj, index);
        return obj;
    }
    
    public void TempblockDataOnDemand.setClientservice(Tempblock obj, int index) {
        Clientservice clientservice = null;
        obj.setClientservice(clientservice);
    }
    
    public void TempblockDataOnDemand.setStartblock(Tempblock obj, int index) {
        Date startblock = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartblock(startblock);
    }
    
    public void TempblockDataOnDemand.setStopblock(Tempblock obj, int index) {
        Date stopblock = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStopblock(stopblock);
    }
    
    public Tempblock TempblockDataOnDemand.getSpecificTempblock(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Tempblock obj = data.get(index);
        Long id = obj.getId();
        return Tempblock.findTempblock(id);
    }
    
    public Tempblock TempblockDataOnDemand.getRandomTempblock() {
        init();
        Tempblock obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Tempblock.findTempblock(id);
    }
    
    public boolean TempblockDataOnDemand.modifyTempblock(Tempblock obj) {
        return false;
    }
    
    public void TempblockDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Tempblock.findTempblockEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Tempblock' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Tempblock>();
        for (int i = 0; i < 10; i++) {
            Tempblock obj = getNewTransientTempblock(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
