// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mihausik.bil;

import com.mihausik.bil.Citystreets;

privileged aspect Citystreets_Roo_JavaBean {
    
    public String Citystreets.getStreet() {
        return this.street;
    }
    
    public void Citystreets.setStreet(String street) {
        this.street = street;
    }
    
}
