// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mihausik.bil;

import com.mihausik.bil.Citystreets;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Citystreets_Roo_Configurable {
    
    declare @type: Citystreets: @Configurable;
    
}
