// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mihausik.bil;

import com.mihausik.bil.Clientservice;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Clientservice_Roo_Configurable {
    
    declare @type: Clientservice: @Configurable;
    
}
