// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mihausik.bil;

import com.mihausik.bil.Clientcontact;

privileged aspect Clientcontact_Roo_JavaBean {
    
    public String Clientcontact.getContact() {
        return this.contact;
    }
    
    public void Clientcontact.setContact(String contact) {
        this.contact = contact;
    }
    
}
