// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mihausik.bil;

import com.mihausik.bil.Clientservicestreet;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Clientservicestreet_Roo_Configurable {
    
    declare @type: Clientservicestreet: @Configurable;
    
}
