// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mihausik.bil;

import com.mihausik.bil.Devicetype;

privileged aspect Devicetype_Roo_JavaBean {
    
    public String Devicetype.getDevtype() {
        return this.devtype;
    }
    
    public void Devicetype.setDevtype(String devtype) {
        this.devtype = devtype;
    }
    
}
