// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mihausik.bil;

import com.mihausik.bil.Statuslica;

privileged aspect Statuslica_Roo_JavaBean {
    
    public String Statuslica.getName() {
        return this.name;
    }
    
    public void Statuslica.setName(String name) {
        this.name = name;
    }
    
}
